// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PegasusMedApi.Server.Data;

#nullable disable

namespace PegasusMedApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PegasusMedApi.Server.Models.MedRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("PegasusMedApi.Server.Models.VendorStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<int?>("MedRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicalRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedRequestId");

                    b.ToTable("VendorStatuses");
                });

            modelBuilder.Entity("PegasusMedApi.Server.Models.VendorStatus", b =>
                {
                    b.HasOne("PegasusMedApi.Server.Models.MedRequest", null)
                        .WithMany("VendorAssignments")
                        .HasForeignKey("MedRequestId");
                });

            modelBuilder.Entity("PegasusMedApi.Server.Models.MedRequest", b =>
                {
                    b.Navigation("VendorAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
